zhukov/webogram

app/css/desktop.css
app/js/directives.js
app/partials/desktop/im.html
app/vendor/jquery.emojiarea/jquery.emojiarea.js

Close #290: show recently used emojis under input area

---

app/index.html

Small OpenGraph fix

---

app/js/controllers.js
app/js/directives.js

Check code value when country was selected. Fix #650

---

app/js/controllers.js
app/js/locales/en-us.json
app/js/services.js
app/partials/desktop/settings_modal.html
app/partials/mobile/settings_modal.html

supported private notifications

---

app/js/lib/polyfill.js

Update console polyfill. Fix #731

---

CONTRIBUTING.md

Add a few fixes from a native English speaker to clarify the "how do changes suggested on a pull request" section. In particular, re-word the title which was non-idiomatic and correct "some times" to "sometimes".
Other edits are minor: clarify "it" in one place and add a missing definite article. Reduce over-use of "do".

CONTRIBUTING: English fixes for PR rebase section

---

app/less/mobile.less

Send button turns green in mobile view. Fix #752

---

app/js/directives.js

Also introduces a "shouldFocusOnInteraction" configuration value to make it easier to understand what the code does and also allow easier changes to this behavior in the future.

Fixes #1000: message box not focused on a computer with touch enabled.

---

app/partials/desktop/im.html

"true" is a wrong attribute value in multiple

Replace wrong attribute value

---

app/js/services.js

Closes https://github.com/zhukov/webogram/issues/1042

Open links starting with https://telegram.me/ in the same window

---

app/js/directives.js

Fixes #1249
I think it should work fine.
Anyway please test it and give me some feedback @wicol @stek29 @steffen-maass

Set different shortcut to switch conversation for mac users. Fixes #1249

---

app/js/lib/ng_utils.js

This is kinda urgent because previous commit broke message sending completely.
See comment on #1267.

Fix dumb errors in previous commit

---

app/js/lib/ng_utils.js

Fixes a bug introduced in #1323
Also changed comment to more clear one.

Fix Android-like format triggers offset calculation

---

app/js/app.js
app/js/controllers.js
app/js/directives.js
app/service_worker.js
gulpfile.js

Fixed the errors that would definitly not change the functionality of the program
These include
* Unexpected && and || combinations
* variables with different values defined in same line of code
* Global variable never defined
* spacing/placing errors
These errors were not touched
* variables who are never used
* == and != errors

Fixed subset of StandardJS errors

---

test/unit/AppImPanelControllerSpec.js
test/unit/AppLangSelectControllerSpec.js
test/unit/AppWelcomeControllerSpec.js
test/unit/DocumentModalControllerSpec.js
test/unit/EmbedModalController.js
test/unit/PhonebookContactsServiceSpec.js
test/unit/VideoModalControllerSpec.js
test/unit/chatTitleFilterSpec.js
test/unit/myHeadDirective.js
test/unit/myLangFooterDirective.js
test/unit/userFirstNameFilterSpec.js
test/unit/userNameFilterSpec.js

In addition to the test, all StandardJS errors in all test files were fixed

Added tests for AppImPanelController, DocumentModalController, EmbedModalController and VideoModalController

---

app/js/messages_manager.js

Fixes #1177
**Working demo**
https://vps.whipermr5.com/webogram/

Update message preview on message edited. Fix #1177

---

app/js/controllers.js
app/partials/desktop/dialog.html

Fixes #1335
**Working demo**
https://vps.whipermr5.com/webogram/

Double click to scroll to bottom of conversation. Fix #1335

---

app/js/controllers.js
app/js/locales/en-us.json
app/js/messages_manager.js
app/partials/desktop/head.html
app/partials/mobile/head.html

Filter for round video messages

---

app/js/lib/mtproto.js

Unused variables #1564

---

app/less/app.less

Fix #1365 View buttons in modal window (reopened PR #1366) 

---

app/js/controllers.js
app/less/desktop.less
app/partials/desktop/dialog.html

Adds multi-forward functionality. Resolves #1492.

Multi-forward functionality #1492

---

README.md

As per package.json: https://github.com/zhukov/webogram/blob/master/package.json#L25

Fix wrong build instruction in readme

---

app/index.html

Resolve https://github.com/zhukov/webogram/issues/1817
@zhukov @stek29

#1817 Resolve facebook metadata issues

---

app/manifest.webapp.json

Remove GA utm_source from webmanifest

---

app/less/app.less

See #1952. This PR fixes positioning of buttons in inline keyboard when buttons are of mixed types (url and callback_data).

Fix positioning of mixed url/callback_data inline buttons (#1952)
