zhukov/webogram

app/js/locales/en-us.json

Please be polite and use the word "remove" 
instead of "kick". We generally do not intend 
to hurt people's sentiments, but "kick" 
sounds abusive.
Thank you. :)
Cheers,
Yesudeep.

Please be polite by using the word "remove" instead of "kick."

---

app/js/directives.js
app/partials/desktop/message.html
app/partials/mobile/message.html

This works pretty well in latest versions of Chrom[e|ium] and Firefox as it's visible in the attached screenshots:
A conversation in Persian **with** this patch:
A conversation in Persian **without** this patch:
related: #182

use dir="auto" to have better RTL support for messages

---

app/js/services.js

```
/^https?:\/\/(?:www\.|m\.)?facebook\.com\/(?:.+?\/posts\/\d+|(?:story\.php|permalink\.php)\?story_fbid=(\d+)(?:&substory_index=\d+)?&id=(\d+))/i;
```
Have tested it on 
https://m.facebook.com/story.php?story_fbid=612064732229087&substory_index=0&id=438429349592627
https://m.facebook.com/story.php?story_fbid=604811292954431&id=438429349592627&p=10
https://www.facebook.com/permalink.php?story_fbid=604811292954431&id=438429349592627
https://www.facebook.com/deblopper/posts/10153177530839188
Facebook Pages without username have the weird url structure. But if we use the id from the weird url and replace it as the username in the normal structure, we get the post. 
```
https://www.facebook.com/"+embedUrlMatches[2]+"/posts/"+embedUrlMatches[1]]
```

More regexes for Facebook

---

app/js/directives.js

Hey. I create a new pull request because I can't reopen the other one.
First commit simply adds a keyboard shortcut (alt + shift + #, where # is in [1..9]) to direct switch between conversations. Fix issue #768
Second commit adds a offset to scrollToDialog function to leave a small portions of adjacent dialogs when switching to non-first and non-last dialogs. So that, now the user can realize if it's not in the first or in the last dialog, giving more Visibility of system status to the user (Nielsen's design principle). I find it more conveniente than scrolling exactly to the dialog.
I was inspired by how firefox manage this with tabs.

Added keyboard shortcut to switch between dialogs. Fix #768

---

Dockerfile

Apparently this is now the way to run the application and get all assets to be served correctly, only noticed this today after updating my local setup again.

Update Dockerfile to work with gulp

---

app/js/filters.js

Fixes #822 . As pointed out, MB would be more accurate, as the value shown is in megabytes (MB) while the symbol used is megabits(Mb).

Fixes #822 Mb to MB for accuracy.

---

app/js/services.js
app/vendor/ui-bootstrap/ui-bootstrap-custom-tpls-0.12.0.js

Ability to temporarily hide prev modal when open a new one.
To test how it works use steps:
1. Open any group chat
2. Open "Group info" modal
3. Click any person from ("Group info" is hidden now, because "Contact info" with backdrop = single)
4. Click "Share contact" link (member modal doesn't hidden, but "Group info" still hidden)
5. Close modal stack in sequence

Modal stack single option

---

package.json

Fix warning during compiling:
```npm WARN package.json Telegram@0.4.7 license should be a valid SPDX license expression```
http://spdx.org/licenses/GPL-3.0.html

Fix warning

---

app/js/directives.js

This adds a call to `MessageComposer.hideSuggestions()` in the
`onMessageSubmit` function so that the autocompleter is always closed after a
message is sent.
On master, create a message like ":D" and send the message. This will trigger
the autocompleter to show up and suggest emojis, but after the message is sent,
the autocompleter will still be visible.
On this branch, sending the same message will close the autocompleter after the
message is sent.
Fix #1203

Hide autocompleter suggestions on message submit

---

app/js/lib/ng_utils.js

\*bold\* and \_italic\_ are now supported too.
Just edited regexp a bit so it matches `` `*_ ``, not only `` ` ``
Then it uses `match[7]` to determine what Entity was parsed.

Add support for bold and italic w/o bots

---

app/partials/desktop/audio_player.html
app/partials/desktop/message_attach_document.html
app/partials/desktop/message_attach_pending.html

Works for audios, documents and pending (uploads).
Not sure if it should be added to mobile partials too. 
Also, not sure if it's needed for other types of attachments.
Please tell me if there's something to fix.
Also not sure if #1034 is needed after this.

Add tooltip to show full file name on hover

---

app/js/message_composer.js
app/less/desktop.less

Fix #1149
In the current style configuration (for desktop), RTL languages are overlapping with the emoji icon.
Here's an example:
LTR before:
RTL before:
LTR after:
RTL after:
though it looks liks the scrollbar is useless since the container expands when you write.
should it be removed alltogether? or after a certain amount of lines it becomes active?
thx for the great tool! :-)

fix scrollbar for RTL languages

---

app/js/lib/ng_utils.js

This switches the shortcuts for bold and italic from single to double asterisks and underscores, just like what Telegram on Android has now.  Users complained about this on Twitter and Telegram's official account responded here: https://twitter.com/telegram/status/817080202257952768
Related discussions: #1285 #1267

Use same format triggers as Android

---

app/partials/mobile/message_service.html

This fixes #1348 by making the mobile modal and desktop modal have the same parameters.

Empty user on invite message in mobile

---

test/unit/AppFooterController.js
test/unit/AppFooterControllerSpec.js
test/unit/ChangelogModalControlelerSpec.js
test/unit/PeerSelectControllerSpec.js

Part of Issue #1354.
This pull request will improve the test scores of the controller.js as follows:
|             | % Statements | % Branch | % Functions | % Lines |
|:-----------:|:------------:|:--------:|:-------------:|:---------:|
|  Currently  |      3.5     |     0    |    0.36     |   3.52  |
| After Merge |      5.61    |    1.16  |    2.88     |   5.64  |
This pull request fully tests the ChangeLogModalController, AppFooterController and PeerSelectController.
If a certain style is demanded for creating tests, then we will adapt the test to conform with the demanded style.
This is also the reason that this pull request tests some of the smaller controllers, in case changes are needed.

Added test for ChangeLogModalController, AppFooterController and PeerSelectController

---

app/js/message_composer.js
app/partials/desktop/composer_dropdown.html

When entering `@$name` an autocomplete shows up showing possible users to mention here. Selecting a user who has set a username for his account will insert `@username` into the composer box. But for users without a dedicated username it will insert
> @1234567 (firstname)
where `1234567` is the internal id of the telegram account and `firstname` is the users first name from the _local_ address book (i.e. how _I_ saved the user in _my_ address book).
In the latter case it is possible to manually change the later to be displayed text for the mention. Although this actually being just a side effect of the implementation I consider this to be **a real feature** and I'd really like to be able to do the same with users which **do** have a username set - especially if it's an uncommon/unknown …

allow editting mentions text for users with usernames

---

app/less/app.less
app/partials/desktop/login.html
app/partials/mobile/login.html

Fixes #1357
Added a close button to both mobile and desktop partial to close the "About" section on Login page.

Added close button to About section on Login page

---

app/js/controllers.js
app/js/directives.js
app/js/lib/utils.js

Small typo in function name, 'hasOnlick' instead of 'hasOnclick'. In the function itself onclick is written without a capital therefore did not place the capital in the function name. Can be changed to 'hasOnClick' if requested.

Renamed 'hasOnlick' to 'hasOnclick', added to StandardJS globals

---

test/unit/filters/myDateFilterSpec.js
test/unit/filters/timeFilterSpec.js

The tests from #1393 had string-solutions for some tests 
However, these tests were fixed for one time-zone: CEST
This created problems for CI frameworks on different timezones (as seen in https://travis-ci.org/bartist/webogram/builds/227096263)
This PR will fix these problems (https://travis-ci.org/bartist/webogram/builds/227108224)

Make filter-tests timezone-independant

---

app/js/background.js

[UI Improvement] Changes color of Chrome OS app window frame to blue.
Before:
After:

Change color of ChromeOS App window to blue. Fix #1403

---

app/js/controllers.js
test/unit/controllers/CountrySelectModalControllerSpec.js
test/unit/controllers/ImportContactModalControllerSpec.js
test/unit/controllers/PasswordRecoveryModalControllerSpec.js
test/unit/controllers/ProfileEditModalControllerSpec.js
test/unit/controllers/UsernameEditModalControllerSpec.js

Relates to #1354 
This PR adds test to improve the test coverage of controller.js to over 10%
The following controllers have been tested:
-  CountrySelectModalController
- ImportContactModalController
- ProfileEditModalController
- PasswordRecoveryModalController
- UsernameEditModalController
UsernameEditModalController misses tests for two scenarios:
- UsernameEditModalController, when the username changes before the check returns feedback, dismisses the positive feedback
- UsernameEditModalController, when the username changes before the check returns feedback, dismisses the error
The test coverage will change as follows:
|             | % Statements | % Branch | % Functions | % Lines |
|:-----------:|:------------:|:--------:|:-------------:|:---------:|
|  Currently  |      6.99   | …

Added tests to improve Controller test coverage to over 10%

---

gulpfile.js

This fixes a caching issue where the app.js files is not cached because it exceeds the maximum file size of sw-precache. 
The `navigateFallback` also will handle all HTML document request which are not directly covered by the cache.

 Fixes #1560

---

app/js/lib/utils.js

Config.LatinizeMap have rule for 'ь' but it is not applied.
Now you can't find russian names with 'ь'. Latinize works incorrect 'илья' translates to 'ilьya'. I found problem with empty string and operator ||.

Fix problem with 'ь' in search

---

README.md
package.json

Not everybody want to have a global install of gulp, when it is not necessary.
So I made proxy scripts in the package.json and enrich the readme accordingly.

Enrich package.json (and Readme) to avoid gulp global install

---

app/js/locales/de-de.json
app/js/locales/en-us.json
app/less/app.less
app/partials/desktop/head.html

The webogram interface has some issues regarding the accessibility for blind users, who use screen reading software. Therefore, the link at the top which is responsible for opening the main menu was not accessible at all.
To solve this, with some help of @dhtstudios, I added the visually-hidden-class and wrote some text into it, in German and English language.

main menu accessible for screen reader

---

app/js/controllers.js

In the international telephone network, the format of telephone numbers is standardized by ITU-T recommendation E.164. This code specifies that the entire number should be 15 digits or shorter.
Very long numbers look weird in the confirmation dialog

Limit login max phone number length
